spring:
  jpa:
    show-sql: true
  application:
    name: schedule-service
  cache:
    cache-names:
    - courses-per-department
  cloud:
    config:
      uri: http://localhost:8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
management:
  security:
    enabled: false
